title: '최우성 포트폴리오'
baseURL: 'https://cws1513.github.io/'

defaultContentLanguage: ko
hasCJKLanguage: true

paginate: 10
summaryLength: 30
enableEmoji: true

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
      - WC_POST_CSS
