# config/_default/menus.en.yaml

main:
  - name: Home
    url: '/'
    weight: 10
  - name: About
    url: '#about'
    weight: 20
  - name: Contact
    url: '#contact'
    weight: 30


  - name: Projects
    identifier: projects 
    weight: 40
    
 
  - name: Portfolio Website Construction
    parent: projects
    url: '/post/portfolio/'
    weight: 3
  - name: Oracle Database Design
    parent: projects
    url: '/post/database/' 
    weight: 2
  - name: Java Naruto Fan Game
    parent: projects
    url: '/post/naruto-game/' 
    weight: 1